version: '3.7'

services:
  db:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      restart_policy:
        condition: on-failure
    networks:
      - web
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: .
    depends_on:
      - db
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - web
    ports:
      - "8000:8000"
    volumes:
      - ./:/deals_reader
    command: sh -c "python manage.py migrate \
      && python manage.py runserver 0.0.0.0:8000 \
      && gunicorn deals_reader.wsgi -bind 0.0.0.0:8000"

  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
        - "6379"
    networks:
      - web


volumes:
  postgres-data:
  .:

networks:
  web:
    driver: overlay
    attachable: true